### ISSUE TITLE
提示“未知表情:w_0005”无法继续，麻烦看看

### ISSUE THREAD

**Issue by asdftij** [cnwangjihe/TiebaBackup#2]
出现问题的帖：http://tieba.baidu.com/p/5195748983，选择了全帖及全评论

**Comment by cnwangjihe** [comment]
现在把未知表情出现时会卡住的问题已经修好了,
但正确下载gif表情暂时还要等一下,
那部分要多加一些特判(因为百度那智障的表情图片路径设计),
我到时再改一下,

**Comment by asdftij** [comment]
> 
> 
> 现在把未知表情出现时会卡住的问题已经修好了,
> 但正确下载gif表情暂时还要等一下,
> 那部分要多加一些特判(因为百度那智障的表情图片路径设计),
> 我到时再改一下,

嗯，我再比较了一下，发现之前还是能爬下全帖的，只是没有完成提示。谢谢您了！

**Comment by CberYellowstone** [comment]
> 现在把未知表情出现时会卡住的问题已经修好了，
> 但正确下载 gif 表情暂时还要等一下，
> 那部分要多加一些特判 (因为百度那智障的表情图片路径设计),
> 我到时再改一下，

这个问题我也遇到了,百度的gif表情确实nc,
我一时之间也想不到什么好办法
虽然能把现有的表情包都加入判定
但是不保证百度加入表情包速度太快
版本更迭时要一直加入新的判定
或许把它当成图片下载是个好主意?
